/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryResponse } from './QueryResponse';
import {
    QueryResponseFromJSON,
    QueryResponseFromJSONTyped,
    QueryResponseToJSON,
    QueryResponseToJSONTyped,
} from './QueryResponse';

/**
 * 
 * @export
 * @interface ExecuteBatchQueries200Response
 */
export interface ExecuteBatchQueries200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ExecuteBatchQueries200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<QueryResponse>}
     * @memberof ExecuteBatchQueries200Response
     */
    results?: Array<QueryResponse>;
    /**
     * 
     * @type {number}
     * @memberof ExecuteBatchQueries200Response
     */
    totalQueries?: number;
    /**
     * 
     * @type {number}
     * @memberof ExecuteBatchQueries200Response
     */
    successfulQueries?: number;
    /**
     * 
     * @type {number}
     * @memberof ExecuteBatchQueries200Response
     */
    failedQueries?: number;
}

/**
 * Check if a given object implements the ExecuteBatchQueries200Response interface.
 */
export function instanceOfExecuteBatchQueries200Response(value: object): value is ExecuteBatchQueries200Response {
    return true;
}

export function ExecuteBatchQueries200ResponseFromJSON(json: any): ExecuteBatchQueries200Response {
    return ExecuteBatchQueries200ResponseFromJSONTyped(json, false);
}

export function ExecuteBatchQueries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteBatchQueries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(QueryResponseFromJSON)),
        'totalQueries': json['total_queries'] == null ? undefined : json['total_queries'],
        'successfulQueries': json['successful_queries'] == null ? undefined : json['successful_queries'],
        'failedQueries': json['failed_queries'] == null ? undefined : json['failed_queries'],
    };
}

export function ExecuteBatchQueries200ResponseToJSON(json: any): ExecuteBatchQueries200Response {
    return ExecuteBatchQueries200ResponseToJSONTyped(json, false);
}

export function ExecuteBatchQueries200ResponseToJSONTyped(value?: ExecuteBatchQueries200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(QueryResponseToJSON)),
        'total_queries': value['totalQueries'],
        'successful_queries': value['successfulQueries'],
        'failed_queries': value['failedQueries'],
    };
}

