/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteBatchQueriesRequest
 */
export interface ExecuteBatchQueriesRequest {
    /**
     * Array of SQL queries to execute
     * @type {Array<string>}
     * @memberof ExecuteBatchQueriesRequest
     */
    queries: Array<string>;
}

/**
 * Check if a given object implements the ExecuteBatchQueriesRequest interface.
 */
export function instanceOfExecuteBatchQueriesRequest(value: object): value is ExecuteBatchQueriesRequest {
    if (!('queries' in value) || value['queries'] === undefined) return false;
    return true;
}

export function ExecuteBatchQueriesRequestFromJSON(json: any): ExecuteBatchQueriesRequest {
    return ExecuteBatchQueriesRequestFromJSONTyped(json, false);
}

export function ExecuteBatchQueriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteBatchQueriesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'queries': json['queries'],
    };
}

export function ExecuteBatchQueriesRequestToJSON(json: any): ExecuteBatchQueriesRequest {
    return ExecuteBatchQueriesRequestToJSONTyped(json, false);
}

export function ExecuteBatchQueriesRequestToJSONTyped(value?: ExecuteBatchQueriesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queries': value['queries'],
    };
}

