/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteQueryRequest
 */
export interface ExecuteQueryRequest {
    /**
     * SQL query to execute
     * @type {string}
     * @memberof ExecuteQueryRequest
     */
    sql: string;
}

/**
 * Check if a given object implements the ExecuteQueryRequest interface.
 */
export function instanceOfExecuteQueryRequest(value: object): value is ExecuteQueryRequest {
    if (!('sql' in value) || value['sql'] === undefined) return false;
    return true;
}

export function ExecuteQueryRequestFromJSON(json: any): ExecuteQueryRequest {
    return ExecuteQueryRequestFromJSONTyped(json, false);
}

export function ExecuteQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sql': json['sql'],
    };
}

export function ExecuteQueryRequestToJSON(json: any): ExecuteQueryRequest {
    return ExecuteQueryRequestToJSONTyped(json, false);
}

export function ExecuteQueryRequestToJSONTyped(value?: ExecuteQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sql': value['sql'],
    };
}

