/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetApiDocs200ResponseEndpointsInner } from './GetApiDocs200ResponseEndpointsInner';
import {
    GetApiDocs200ResponseEndpointsInnerFromJSON,
    GetApiDocs200ResponseEndpointsInnerFromJSONTyped,
    GetApiDocs200ResponseEndpointsInnerToJSON,
    GetApiDocs200ResponseEndpointsInnerToJSONTyped,
} from './GetApiDocs200ResponseEndpointsInner';

/**
 * 
 * @export
 * @interface GetApiDocs200Response
 */
export interface GetApiDocs200Response {
    /**
     * 
     * @type {Array<GetApiDocs200ResponseEndpointsInner>}
     * @memberof GetApiDocs200Response
     */
    endpoints?: Array<GetApiDocs200ResponseEndpointsInner>;
}

/**
 * Check if a given object implements the GetApiDocs200Response interface.
 */
export function instanceOfGetApiDocs200Response(value: object): value is GetApiDocs200Response {
    return true;
}

export function GetApiDocs200ResponseFromJSON(json: any): GetApiDocs200Response {
    return GetApiDocs200ResponseFromJSONTyped(json, false);
}

export function GetApiDocs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiDocs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoints': json['endpoints'] == null ? undefined : ((json['endpoints'] as Array<any>).map(GetApiDocs200ResponseEndpointsInnerFromJSON)),
    };
}

export function GetApiDocs200ResponseToJSON(json: any): GetApiDocs200Response {
    return GetApiDocs200ResponseToJSONTyped(json, false);
}

export function GetApiDocs200ResponseToJSONTyped(value?: GetApiDocs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoints': value['endpoints'] == null ? undefined : ((value['endpoints'] as Array<any>).map(GetApiDocs200ResponseEndpointsInnerToJSON)),
    };
}

