/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiDocs200ResponseEndpointsInner
 */
export interface GetApiDocs200ResponseEndpointsInner {
    /**
     * 
     * @type {string}
     * @memberof GetApiDocs200ResponseEndpointsInner
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiDocs200ResponseEndpointsInner
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiDocs200ResponseEndpointsInner
     */
    description?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof GetApiDocs200ResponseEndpointsInner
     */
    parameters?: Array<object>;
    /**
     * 
     * @type {object}
     * @memberof GetApiDocs200ResponseEndpointsInner
     */
    requestBody?: object;
    /**
     * 
     * @type {object}
     * @memberof GetApiDocs200ResponseEndpointsInner
     */
    responses?: object;
}

/**
 * Check if a given object implements the GetApiDocs200ResponseEndpointsInner interface.
 */
export function instanceOfGetApiDocs200ResponseEndpointsInner(value: object): value is GetApiDocs200ResponseEndpointsInner {
    return true;
}

export function GetApiDocs200ResponseEndpointsInnerFromJSON(json: any): GetApiDocs200ResponseEndpointsInner {
    return GetApiDocs200ResponseEndpointsInnerFromJSONTyped(json, false);
}

export function GetApiDocs200ResponseEndpointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiDocs200ResponseEndpointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'method': json['method'] == null ? undefined : json['method'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'requestBody': json['request_body'] == null ? undefined : json['request_body'],
        'responses': json['responses'] == null ? undefined : json['responses'],
    };
}

export function GetApiDocs200ResponseEndpointsInnerToJSON(json: any): GetApiDocs200ResponseEndpointsInner {
    return GetApiDocs200ResponseEndpointsInnerToJSONTyped(json, false);
}

export function GetApiDocs200ResponseEndpointsInnerToJSONTyped(value?: GetApiDocs200ResponseEndpointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'method': value['method'],
        'description': value['description'],
        'parameters': value['parameters'],
        'request_body': value['requestBody'],
        'responses': value['responses'],
    };
}

