/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServiceStatus200Response
 */
export interface GetServiceStatus200Response {
    /**
     * 
     * @type {string}
     * @memberof GetServiceStatus200Response
     */
    status?: GetServiceStatus200ResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof GetServiceStatus200Response
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof GetServiceStatus200Response
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof GetServiceStatus200Response
     */
    database?: string;
    /**
     * 
     * @type {string}
     * @memberof GetServiceStatus200Response
     */
    uptime?: string;
    /**
     * 
     * @type {number}
     * @memberof GetServiceStatus200Response
     */
    connections?: number;
}


/**
 * @export
 */
export const GetServiceStatus200ResponseStatusEnum = {
    Running: 'running',
    Stopped: 'stopped',
    Starting: 'starting',
    Stopping: 'stopping'
} as const;
export type GetServiceStatus200ResponseStatusEnum = typeof GetServiceStatus200ResponseStatusEnum[keyof typeof GetServiceStatus200ResponseStatusEnum];


/**
 * Check if a given object implements the GetServiceStatus200Response interface.
 */
export function instanceOfGetServiceStatus200Response(value: object): value is GetServiceStatus200Response {
    return true;
}

export function GetServiceStatus200ResponseFromJSON(json: any): GetServiceStatus200Response {
    return GetServiceStatus200ResponseFromJSONTyped(json, false);
}

export function GetServiceStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServiceStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'port': json['port'] == null ? undefined : json['port'],
        'host': json['host'] == null ? undefined : json['host'],
        'database': json['database'] == null ? undefined : json['database'],
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
        'connections': json['connections'] == null ? undefined : json['connections'],
    };
}

export function GetServiceStatus200ResponseToJSON(json: any): GetServiceStatus200Response {
    return GetServiceStatus200ResponseToJSONTyped(json, false);
}

export function GetServiceStatus200ResponseToJSONTyped(value?: GetServiceStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'port': value['port'],
        'host': value['host'],
        'database': value['database'],
        'uptime': value['uptime'],
        'connections': value['connections'],
    };
}

