/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallPluginRequest
 */
export interface InstallPluginRequest {
    /**
     * Plugin name to install
     * @type {string}
     * @memberof InstallPluginRequest
     */
    name: string;
    /**
     * Specific version to install (optional)
     * @type {string}
     * @memberof InstallPluginRequest
     */
    version?: string;
}

/**
 * Check if a given object implements the InstallPluginRequest interface.
 */
export function instanceOfInstallPluginRequest(value: object): value is InstallPluginRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function InstallPluginRequestFromJSON(json: any): InstallPluginRequest {
    return InstallPluginRequestFromJSONTyped(json, false);
}

export function InstallPluginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallPluginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function InstallPluginRequestToJSON(json: any): InstallPluginRequest {
    return InstallPluginRequestToJSONTyped(json, false);
}

export function InstallPluginRequestToJSONTyped(value?: InstallPluginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
    };
}

