/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginInfo } from './PluginInfo';
import {
    PluginInfoFromJSON,
    PluginInfoFromJSONTyped,
    PluginInfoToJSON,
    PluginInfoToJSONTyped,
} from './PluginInfo';

/**
 * 
 * @export
 * @interface ListPlugins200Response
 */
export interface ListPlugins200Response {
    /**
     * 
     * @type {Array<PluginInfo>}
     * @memberof ListPlugins200Response
     */
    plugins?: Array<PluginInfo>;
    /**
     * 
     * @type {number}
     * @memberof ListPlugins200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the ListPlugins200Response interface.
 */
export function instanceOfListPlugins200Response(value: object): value is ListPlugins200Response {
    return true;
}

export function ListPlugins200ResponseFromJSON(json: any): ListPlugins200Response {
    return ListPlugins200ResponseFromJSONTyped(json, false);
}

export function ListPlugins200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPlugins200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'plugins': json['plugins'] == null ? undefined : ((json['plugins'] as Array<any>).map(PluginInfoFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListPlugins200ResponseToJSON(json: any): ListPlugins200Response {
    return ListPlugins200ResponseToJSONTyped(json, false);
}

export function ListPlugins200ResponseToJSONTyped(value?: ListPlugins200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plugins': value['plugins'] == null ? undefined : ((value['plugins'] as Array<any>).map(PluginInfoToJSON)),
        'total': value['total'],
    };
}

