/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginInfo
 */
export interface PluginInfo {
    /**
     * Plugin name
     * @type {string}
     * @memberof PluginInfo
     */
    name?: string;
    /**
     * Plugin version
     * @type {string}
     * @memberof PluginInfo
     */
    version?: string;
    /**
     * Available connections for this plugin
     * @type {Array<string>}
     * @memberof PluginInfo
     */
    connections?: Array<string>;
    /**
     * Plugin installation status
     * @type {string}
     * @memberof PluginInfo
     */
    status?: PluginInfoStatusEnum;
}


/**
 * @export
 */
export const PluginInfoStatusEnum = {
    Installed: 'installed',
    Failed: 'failed',
    Updating: 'updating'
} as const;
export type PluginInfoStatusEnum = typeof PluginInfoStatusEnum[keyof typeof PluginInfoStatusEnum];


/**
 * Check if a given object implements the PluginInfo interface.
 */
export function instanceOfPluginInfo(value: object): value is PluginInfo {
    return true;
}

export function PluginInfoFromJSON(json: any): PluginInfo {
    return PluginInfoFromJSONTyped(json, false);
}

export function PluginInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'connections': json['connections'] == null ? undefined : json['connections'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PluginInfoToJSON(json: any): PluginInfo {
    return PluginInfoToJSONTyped(json, false);
}

export function PluginInfoToJSONTyped(value?: PluginInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'connections': value['connections'],
        'status': value['status'],
    };
}

