/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimingInfo } from './TimingInfo';
import {
    TimingInfoFromJSON,
    TimingInfoFromJSONTyped,
    TimingInfoToJSON,
    TimingInfoToJSONTyped,
} from './TimingInfo';

/**
 * 
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
    /**
     * Whether the query executed successfully
     * @type {boolean}
     * @memberof QueryResponse
     */
    success?: boolean;
    /**
     * Query results as an array of objects
     * @type {Array<{ [key: string]: any; }>}
     * @memberof QueryResponse
     */
    data?: Array<{ [key: string]: any; }>;
    /**
     * Column names from the query result
     * @type {Array<string>}
     * @memberof QueryResponse
     */
    columns?: Array<string>;
    /**
     * Number of rows returned
     * @type {number}
     * @memberof QueryResponse
     */
    rowCount?: number;
    /**
     * 
     * @type {TimingInfo}
     * @memberof QueryResponse
     */
    timing?: TimingInfo;
    /**
     * Error message if the query failed
     * @type {string}
     * @memberof QueryResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the QueryResponse interface.
 */
export function instanceOfQueryResponse(value: object): value is QueryResponse {
    return true;
}

export function QueryResponseFromJSON(json: any): QueryResponse {
    return QueryResponseFromJSONTyped(json, false);
}

export function QueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : json['data'],
        'columns': json['columns'] == null ? undefined : json['columns'],
        'rowCount': json['row_count'] == null ? undefined : json['row_count'],
        'timing': json['timing'] == null ? undefined : TimingInfoFromJSON(json['timing']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function QueryResponseToJSON(json: any): QueryResponse {
    return QueryResponseToJSONTyped(json, false);
}

export function QueryResponseToJSONTyped(value?: QueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
        'columns': value['columns'],
        'row_count': value['rowCount'],
        'timing': TimingInfoToJSON(value['timing']),
        'error': value['error'],
    };
}

