/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestartService200Response
 */
export interface RestartService200Response {
    /**
     * 
     * @type {boolean}
     * @memberof RestartService200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RestartService200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof RestartService200Response
     */
    port?: number;
}

/**
 * Check if a given object implements the RestartService200Response interface.
 */
export function instanceOfRestartService200Response(value: object): value is RestartService200Response {
    return true;
}

export function RestartService200ResponseFromJSON(json: any): RestartService200Response {
    return RestartService200ResponseFromJSONTyped(json, false);
}

export function RestartService200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestartService200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'port': json['port'] == null ? undefined : json['port'],
    };
}

export function RestartService200ResponseToJSON(json: any): RestartService200Response {
    return RestartService200ResponseToJSONTyped(json, false);
}

export function RestartService200ResponseToJSONTyped(value?: RestartService200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'port': value['port'],
    };
}

