/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimingInfo
 */
export interface TimingInfo {
    /**
     * Query execution time in milliseconds
     * @type {number}
     * @memberof TimingInfo
     */
    durationMs?: number;
    /**
     * Number of rows returned by the query
     * @type {number}
     * @memberof TimingInfo
     */
    rowsReturned?: number;
    /**
     * Number of rows fetched from the source (not cached)
     * @type {number}
     * @memberof TimingInfo
     */
    uncachedRowsFetched?: number;
    /**
     * Number of rows fetched from cache
     * @type {number}
     * @memberof TimingInfo
     */
    cachedRowsFetched?: number;
    /**
     * Number of hydrate function calls made
     * @type {number}
     * @memberof TimingInfo
     */
    hydrateCalls?: number;
    /**
     * Number of connections used
     * @type {number}
     * @memberof TimingInfo
     */
    connectionCount?: number;
}

/**
 * Check if a given object implements the TimingInfo interface.
 */
export function instanceOfTimingInfo(value: object): value is TimingInfo {
    return true;
}

export function TimingInfoFromJSON(json: any): TimingInfo {
    return TimingInfoFromJSONTyped(json, false);
}

export function TimingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'rowsReturned': json['rows_returned'] == null ? undefined : json['rows_returned'],
        'uncachedRowsFetched': json['uncached_rows_fetched'] == null ? undefined : json['uncached_rows_fetched'],
        'cachedRowsFetched': json['cached_rows_fetched'] == null ? undefined : json['cached_rows_fetched'],
        'hydrateCalls': json['hydrate_calls'] == null ? undefined : json['hydrate_calls'],
        'connectionCount': json['connection_count'] == null ? undefined : json['connection_count'],
    };
}

export function TimingInfoToJSON(json: any): TimingInfo {
    return TimingInfoToJSONTyped(json, false);
}

export function TimingInfoToJSONTyped(value?: TimingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_ms': value['durationMs'],
        'rows_returned': value['rowsReturned'],
        'uncached_rows_fetched': value['uncachedRowsFetched'],
        'cached_rows_fetched': value['cachedRowsFetched'],
        'hydrate_calls': value['hydrateCalls'],
        'connection_count': value['connectionCount'],
    };
}

