/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePluginRequest
 */
export interface UpdatePluginRequest {
    /**
     * Plugin name to update
     * @type {string}
     * @memberof UpdatePluginRequest
     */
    name: string;
    /**
     * Specific version to update to (optional)
     * @type {string}
     * @memberof UpdatePluginRequest
     */
    version?: string;
}

/**
 * Check if a given object implements the UpdatePluginRequest interface.
 */
export function instanceOfUpdatePluginRequest(value: object): value is UpdatePluginRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdatePluginRequestFromJSON(json: any): UpdatePluginRequest {
    return UpdatePluginRequestFromJSONTyped(json, false);
}

export function UpdatePluginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePluginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function UpdatePluginRequestToJSON(json: any): UpdatePluginRequest {
    return UpdatePluginRequestToJSONTyped(json, false);
}

export function UpdatePluginRequestToJSONTyped(value?: UpdatePluginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
    };
}

