/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginInfo } from './PluginInfo';
import {
    PluginInfoFromJSON,
    PluginInfoFromJSONTyped,
    PluginInfoToJSON,
    PluginInfoToJSONTyped,
} from './PluginInfo';

/**
 * 
 * @export
 * @interface UpdatePlugin200Response
 */
export interface UpdatePlugin200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePlugin200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdatePlugin200Response
     */
    message?: string;
    /**
     * 
     * @type {PluginInfo}
     * @memberof UpdatePlugin200Response
     */
    plugin?: PluginInfo;
}

/**
 * Check if a given object implements the UpdatePlugin200Response interface.
 */
export function instanceOfUpdatePlugin200Response(value: object): value is UpdatePlugin200Response {
    return true;
}

export function UpdatePlugin200ResponseFromJSON(json: any): UpdatePlugin200Response {
    return UpdatePlugin200ResponseFromJSONTyped(json, false);
}

export function UpdatePlugin200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlugin200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'plugin': json['plugin'] == null ? undefined : PluginInfoFromJSON(json['plugin']),
    };
}

export function UpdatePlugin200ResponseToJSON(json: any): UpdatePlugin200Response {
    return UpdatePlugin200ResponseToJSONTyped(json, false);
}

export function UpdatePlugin200ResponseToJSONTyped(value?: UpdatePlugin200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'plugin': PluginInfoToJSON(value['plugin']),
    };
}

