/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetApiDocs200Response,
} from '../models/index';
import {
    GetApiDocs200ResponseFromJSON,
    GetApiDocs200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DocumentationApi extends runtime.BaseAPI {

    /**
     * Get comprehensive API documentation and endpoint information
     * API Documentation
     */
    async getApiDocsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetApiDocs200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/docs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetApiDocs200ResponseFromJSON(jsonValue));
    }

    /**
     * Get comprehensive API documentation and endpoint information
     * API Documentation
     */
    async getApiDocs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetApiDocs200Response> {
        const response = await this.getApiDocsRaw(initOverrides);
        return await response.value();
    }

}
