/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  InstallPlugin200Response,
  InstallPluginRequest,
  ListPlugins200Response,
  UninstallPlugin200Response,
  UpdatePlugin200Response,
  UpdatePluginRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    InstallPlugin200ResponseFromJSON,
    InstallPlugin200ResponseToJSON,
    InstallPluginRequestFromJSON,
    InstallPluginRequestToJSON,
    ListPlugins200ResponseFromJSON,
    ListPlugins200ResponseToJSON,
    UninstallPlugin200ResponseFromJSON,
    UninstallPlugin200ResponseToJSON,
    UpdatePlugin200ResponseFromJSON,
    UpdatePlugin200ResponseToJSON,
    UpdatePluginRequestFromJSON,
    UpdatePluginRequestToJSON,
} from '../models/index';

export interface InstallPluginOperationRequest {
    installPluginRequest: InstallPluginRequest;
}

export interface UninstallPluginRequest {
    name: string;
}

export interface UpdatePluginOperationRequest {
    updatePluginRequest: UpdatePluginRequest;
}

/**
 * 
 */
export class PluginManagementApi extends runtime.BaseAPI {

    /**
     * Install a new Steampipe plugin
     * Install Plugin
     */
    async installPluginRaw(requestParameters: InstallPluginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstallPlugin200Response>> {
        if (requestParameters['installPluginRequest'] == null) {
            throw new runtime.RequiredError(
                'installPluginRequest',
                'Required parameter "installPluginRequest" was null or undefined when calling installPlugin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/plugins/install`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InstallPluginRequestToJSON(requestParameters['installPluginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstallPlugin200ResponseFromJSON(jsonValue));
    }

    /**
     * Install a new Steampipe plugin
     * Install Plugin
     */
    async installPlugin(requestParameters: InstallPluginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstallPlugin200Response> {
        const response = await this.installPluginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of all installed Steampipe plugins
     * List Plugins
     */
    async listPluginsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPlugins200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/plugins`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPlugins200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of all installed Steampipe plugins
     * List Plugins
     */
    async listPlugins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPlugins200Response> {
        const response = await this.listPluginsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Uninstall a Steampipe plugin
     * Uninstall Plugin
     */
    async uninstallPluginRaw(requestParameters: UninstallPluginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UninstallPlugin200Response>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling uninstallPlugin().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/plugins/uninstall`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UninstallPlugin200ResponseFromJSON(jsonValue));
    }

    /**
     * Uninstall a Steampipe plugin
     * Uninstall Plugin
     */
    async uninstallPlugin(requestParameters: UninstallPluginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UninstallPlugin200Response> {
        const response = await this.uninstallPluginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a Steampipe plugin to the latest version
     * Update Plugin
     */
    async updatePluginRaw(requestParameters: UpdatePluginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdatePlugin200Response>> {
        if (requestParameters['updatePluginRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePluginRequest',
                'Required parameter "updatePluginRequest" was null or undefined when calling updatePlugin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/plugins/update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePluginRequestToJSON(requestParameters['updatePluginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdatePlugin200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a Steampipe plugin to the latest version
     * Update Plugin
     */
    async updatePlugin(requestParameters: UpdatePluginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdatePlugin200Response> {
        const response = await this.updatePluginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
