/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ExecuteBatchQueries200Response,
  ExecuteBatchQueriesRequest,
  ExecuteQueryRequest,
  QueryResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecuteBatchQueries200ResponseFromJSON,
    ExecuteBatchQueries200ResponseToJSON,
    ExecuteBatchQueriesRequestFromJSON,
    ExecuteBatchQueriesRequestToJSON,
    ExecuteQueryRequestFromJSON,
    ExecuteQueryRequestToJSON,
    QueryResponseFromJSON,
    QueryResponseToJSON,
} from '../models/index';

export interface ExecuteBatchQueriesOperationRequest {
    executeBatchQueriesRequest: ExecuteBatchQueriesRequest;
}

export interface ExecuteQueryOperationRequest {
    executeQueryRequest: ExecuteQueryRequest;
}

/**
 * 
 */
export class QueryApi extends runtime.BaseAPI {

    /**
     * Execute multiple SQL queries in a single request
     * Execute Batch Queries
     */
    async executeBatchQueriesRaw(requestParameters: ExecuteBatchQueriesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecuteBatchQueries200Response>> {
        if (requestParameters['executeBatchQueriesRequest'] == null) {
            throw new runtime.RequiredError(
                'executeBatchQueriesRequest',
                'Required parameter "executeBatchQueriesRequest" was null or undefined when calling executeBatchQueries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/query/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecuteBatchQueriesRequestToJSON(requestParameters['executeBatchQueriesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecuteBatchQueries200ResponseFromJSON(jsonValue));
    }

    /**
     * Execute multiple SQL queries in a single request
     * Execute Batch Queries
     */
    async executeBatchQueries(requestParameters: ExecuteBatchQueriesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecuteBatchQueries200Response> {
        const response = await this.executeBatchQueriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Execute a single SQL query and return results in JSON format.  The query can access any tables provided by installed Steampipe plugins (e.g., AWS resources, Kubernetes objects, database tables, etc.). 
     * Execute SQL Query
     */
    async executeQueryRaw(requestParameters: ExecuteQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        if (requestParameters['executeQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'executeQueryRequest',
                'Required parameter "executeQueryRequest" was null or undefined when calling executeQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/query`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecuteQueryRequestToJSON(requestParameters['executeQueryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Execute a single SQL query and return results in JSON format.  The query can access any tables provided by installed Steampipe plugins (e.g., AWS resources, Kubernetes objects, database tables, etc.). 
     * Execute SQL Query
     */
    async executeQuery(requestParameters: ExecuteQueryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.executeQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
