/* tslint:disable */
/* eslint-disable */
/**
 * DevOps REST API
 * REST API for DevOps - a universal query interface for cloud APIs, databases, and services.  This API provides programmatic access to Steampipe\'s query execution, plugin management, and service management capabilities.  ## Features - Execute SQL queries against cloud resources and databases - Manage DevOps plugins (install, uninstall, update, list) - Control DevOps database service (start, stop, restart, status) - Batch query execution - Health monitoring  ## Authentication This API runs in local mode and does not require cloud authentication.  ## Prerequisites - DevOps database service must be running (`steampipe service start`) - Appropriate plugins must be installed for the resources you want to query 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetServiceStatus200Response,
  RestartService200Response,
  StartService200Response,
  StopService200Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetServiceStatus200ResponseFromJSON,
    GetServiceStatus200ResponseToJSON,
    RestartService200ResponseFromJSON,
    RestartService200ResponseToJSON,
    StartService200ResponseFromJSON,
    StartService200ResponseToJSON,
    StopService200ResponseFromJSON,
    StopService200ResponseToJSON,
} from '../models/index';

export interface RestartServiceRequest {
    port?: number;
    listenAddresses?: string;
}

export interface StartServiceRequest {
    port?: number;
    listenAddresses?: string;
}

export interface StopServiceRequest {
    force?: boolean;
}

/**
 * 
 */
export class ServiceManagementApi extends runtime.BaseAPI {

    /**
     * Get the current status of the DevOps database service
     * Get Service Status
     */
    async getServiceStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetServiceStatus200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/service/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetServiceStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Get the current status of the DevOps database service
     * Get Service Status
     */
    async getServiceStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetServiceStatus200Response> {
        const response = await this.getServiceStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Restart the Steampipe database service
     * Restart Service
     */
    async restartServiceRaw(requestParameters: RestartServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RestartService200Response>> {
        const queryParameters: any = {};

        if (requestParameters['port'] != null) {
            queryParameters['port'] = requestParameters['port'];
        }

        if (requestParameters['listenAddresses'] != null) {
            queryParameters['listen_addresses'] = requestParameters['listenAddresses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/service/restart`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RestartService200ResponseFromJSON(jsonValue));
    }

    /**
     * Restart the Steampipe database service
     * Restart Service
     */
    async restartService(requestParameters: RestartServiceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RestartService200Response> {
        const response = await this.restartServiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start the Steampipe database service
     * Start Service
     */
    async startServiceRaw(requestParameters: StartServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartService200Response>> {
        const queryParameters: any = {};

        if (requestParameters['port'] != null) {
            queryParameters['port'] = requestParameters['port'];
        }

        if (requestParameters['listenAddresses'] != null) {
            queryParameters['listen_addresses'] = requestParameters['listenAddresses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/service/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartService200ResponseFromJSON(jsonValue));
    }

    /**
     * Start the Steampipe database service
     * Start Service
     */
    async startService(requestParameters: StartServiceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartService200Response> {
        const response = await this.startServiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop the Steampipe database service
     * Stop Service
     */
    async stopServiceRaw(requestParameters: StopServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopService200Response>> {
        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/service/stop`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopService200ResponseFromJSON(jsonValue));
    }

    /**
     * Stop the Steampipe database service
     * Stop Service
     */
    async stopService(requestParameters: StopServiceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopService200Response> {
        const response = await this.stopServiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
